#!/bin/bash

# path
SOURCE_DIR=${USER}/target/riscv64gc-unknown-none-elf/${TYPE_DIR}
TARGET_DIR=${KERNEL}/src

#important file
BIN_FILE=(` ls  ${SOURCE_DIR} --color=never -1 -F | grep -e "\.bin\*$" | tr '\*' ' ' | tr '\n' ' '`)
LINK_APP_ASM=${TARGET_DIR}/link_app.asm

FILE_COUNT=${#BIN_FILE[@]}

#create file
echo "# The file is generated by linker.sh"> ${LINK_APP_ASM}

# start
echo "
    .align 3
    .section .data
    .global _num_app
_num_app:
    .quad ${FILE_COUNT}" >> ${LINK_APP_ASM}

if [ ${FILE_COUNT} -ne 0 ]; then
    for ((i=0;i<${FILE_COUNT};i++)); do
        printf "    .quad app_${i}_start\n" >> ${LINK_APP_ASM}
    done
    printf "    .quad app_$((FILE_COUNT-1))_end \n" >> ${LINK_APP_ASM}
else
    exit 0
fi

for ((i=0;i<${FILE_COUNT};i++)); do
    printf "
    .section .data
    .global app_${i}_start
    .global app_${i}_end
app_${i}_start:
    .incbin \"${SOURCE_DIR}/${BIN_FILE[$i]}\"
app_${i}_end:
" >> ${LINK_APP_ASM}
done










