[package]
name = "os"
version = "0.1.0"
authors = ["zsiothsu <zsiothsu@zhishan-iot.tk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
